### PR TITLE
Update to use lodash modules

### PR DESCRIPTION
**Pull request by legastero**

### CODE REVIEW

**Comment by fyockm** [comment]
+1

**Comment by wraithgar** [comment]
+1

**Comment by wraithgar** [comment]
can you patch release this @latentflip?

**Comment by latentflip** [comment]
Oh no I don't think I can I tried but npm kept failing. I think I'm not an owner + @henrikjoreteg

Philip Roberts
&yet

**Comment by fyockm** [comment]
Yep, looks like Henrik is the only maintainer: https://www.npmjs.com/package/ampersand-app

**Comment by HenrikJoreteg** [comment]
fixed, sorry

**Comment by lukekarrys** [comment]
Published as `v1.0.4`

**Pull request merged**
