### PR TITLE
Bump dependencies including lodash v4

### PR DESCRIPTION
**Pull request by samhashemi**
I'd like to go through and update all the ampersand modules to use lodash v4. Is there a recommended order? Lots of modules seem to depend on other modules.

### CODE REVIEW

**Comment by samhashemi** [comment]
@cdaringe @wraithgar can you take a look and recommend next steps? I'd like to get everything to lodash v4 asap.

**Comment by cdaringe** [comment]
tests pass locally. +1

**Comment by cdaringe** [comment]
@samhashemi, no rigid next steps. when the PRs are ready and the deps g2g, ping us and we'll get 'em published.  unifying the lodash dep is simple enough :)

**Comment by pgilad** [comment]
+1

**Comment by samhashemi** [comment]
Thanks for merging @pgilad. Can you also bump the npm version?

**Comment by pgilad** [comment]
@AmpersandJS/core-team I pushed version 2.0.0 (https://github.com/AmpersandJS/ampersand-app/commit/40378666843d202b6f0881e042ddd4bfe02da106) but can't publish it to npm. Can anyone take care of that?

**Comment by fyockm** [comment]
I _think_ I have npm permissions for this package- let me try.

Thanks @samhashemi for the work and @pgilad for merging!

**Comment by fyockm** [comment]
Well, looks like I was mistaken and don't have npm perms here.

Side note: I get the warning below when running `npm install`.  Should it be `phantomjs-prebuilt` instead of `phantomjs`?

```
npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. 
  Please update 'phantomjs' package references to 'phantomjs-prebuilt'
```

**Comment by lukekarrys** [comment]
@fyockm @pgilad I added you both to npm for this project. Ping me if you find any others that you need.

**Comment by fyockm** [comment]
Published - thanks @lukekarrys!

**Comment by lukekarrys** [comment]
Also, I'm going to go through the rest of the modules and try to get major versions of everything lodash4 related published today.

**Comment by samhashemi** [comment]
@lukekarrys thanks! appreciate the help!

**Comment by lukekarrys** [comment]
So I think I got to everything yesterday (except for ampersand-view which should get done today, see https://github.com/AmpersandJS/ampersand-view/issues/176). Hopefully we are all Lodash 4-ified now! @samhashemi thanks for all your hard work in this. Let me know if anything is missing.

**Pull request merged**
