### PR TITLE
use individual lodash modules

### PR DESCRIPTION
**Pull request by wraithgar**
Was doing an audit of one of my apps this week and noticed this module was bringing in ALL of lodash with it, that's > 200k of code I don't need, personally.

Not sure if there was a specific reason or bringing it in but this PR takes it back to the single-repo-per-method we were doing w/ lodash 3.

### CODE REVIEW

**Comment by wraithgar** [comment]
Build is failing on the push due to a failed call to localtunnel.me, which if I recall correctly had been phased out of the other ampersand modules for this reason.

**Comment by cdaringe** [comment]
Gar your bundler shouldn't bundle all of lodash the way it was.  In fact, the bundle should be smaller the way it was vs what you're reverting to, per JDD

**Comment by wraithgar** [comment]
Hmm ok that's odd. I'm using [https://www.npmjs.com/package/disc](disc) to analyze the bundle straight from browserify using:

`browserify --full-paths -t [ jadeify --doctype html ] client/app.js | discify --open`

I'll see if there's any more documentation before pushing back on this, thanks

**Comment by cdaringe** [comment]
i used browserify to gen the bundles i mention over [here](https://github.com/AmpersandJS/ampersand-state/issues/230#issuecomment-201170895)

**Comment by wraithgar** [comment]
Yeah thanks for the follow up, after looking at the built file on disk and the reports from the disc app, disc is overreporting on size, including the entire module even if it doesn't end up in the bundle.  False positive, thanks.

**Pull request closed without merging**
